// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameOutcome } from "./GameOutcome";
import type { GameReason } from "./GameReason";

export type AddNumbersGameStatus = "SetupParticipants" | "PlaceBet" | "SetupFunding" | "CreateProgram" | "SubmitSum" | { "GameComplete": { outcome: GameOutcome, reason: GameReason, } } | "Finished";
