// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddNumbersGameStatus } from "./AddNumbersGameStatus";
import type { BitVMXProgramProperties } from "./BitVMXProgramProperties";
import type { PlayerRole } from "./PlayerRole";

export type AddNumbersGame = { program_id: string, role: PlayerRole, number1: number | null, number2: number | null, guess: number | null, status: AddNumbersGameStatus, created_at: bigint, updated_at: bigint, bitvmx_program_properties: BitVMXProgramProperties, };
