// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddNumbersGameStatus } from "./AddNumbersGameStatus";

export type AddNumbersGame = { id: string, player1: string, player2: string, number1: number | null, number2: number | null, guess: number | null, status: AddNumbersGameStatus, created_at: bigint, updated_at: bigint, };
