// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AddNumbersGameStatus = "WaitingForNumbers" | "WaitingForGuess" | { "Won": { winner: string, } } | { "Lost": { correct_answer: number, } };
