// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { P2PAddress } from "./P2PAddress";

export type AggregatedKeySubmission = { uuid: string, p2p_addresses: Array<P2PAddress>, operator_keys: Array<string> | null, leader_idx: number, };
