// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AggregatedKeyResponse = { 
/**
 * The UUID of the aggregated key
 */
uuid: string, 
/**
 * The aggregated public key in hex format
 */
aggregated_key: string, };
