// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { P2PAddress } from "./P2PAddress";

export type AggregatedKeyRequest = { 
/**
 * The UUID of the aggregated key
 */
uuid: string, 
/**
 * The P2P addresses of the bitvmx nodes in the aggregated key
 */
p2p_addresses: Array<P2PAddress>, 
/**
 * The operator keys in hex format
 */
operator_keys: Array<string> | null, 
/**
 * The leader index of the aggregated key
 */
leader_idx: number, };
