// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { P2PAddress } from "./P2PAddress";
import type { Utxo } from "./Utxo";
import type { JsonValue } from "./serde_json/JsonValue";

export type BitVMXProgramProperties = { aggregated_key: string, aggregated_id: string, protocol_address: string, participants_addresses: Array<P2PAddress>, participants_keys: Array<string>, funding_protocol_utxo: Utxo | null, funding_bet_utxo: Utxo | null, txs: { [key in string]?: JsonValue }, };
