// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Utxo } from "./Utxo";

export type FundingUtxosResponse = { funding_protocol_utxo: Utxo | null, funding_bet_utxo: Utxo | null, };
