// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Utxo } from "./Utxo";

export type FundingUtxoRequest = { program_id: string, funding_protocol_utxo: Utxo, funding_bet_utxo: Utxo, };
