// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameStatus } from "./GameStatus";
import type { Move } from "./Move";
import type { Player } from "./Player";

export type Game = { id: string, board: [[Player | null, Player | null, Player | null], [Player | null, Player | null, Player | null], [Player | null, Player | null, Player | null]], current_player: Player, status: GameStatus, moves: Array<Move>, created_at: bigint, updated_at: bigint, };
