// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameStatus } from "./GameStatus";
import type { Player } from "./Player";

export type GameStatusResponse = { status: GameStatus, current_player: Player | null, };
