// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Player } from "./Player";
import type { Position } from "./Position";

export type MakeMoveRequest = { player: Player, position: Position, };
