// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Utxo } from "./Utxo";

export type MyFundingUtxoResponse = { 
/**
 * The funding UTXO for the current participant
 */
utxo: Utxo, };
