// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OperatorKeys = { 
/**
 * The public key in hex format
 */
pub_key: string, 
/**
 * The funding key in hex format
 */
funding_key: string, };
