// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Utxo } from "./Utxo";

export type OtherParticipantFundingUtxoRequest = { 
/**
 * The other participant's funding UTXO
 */
utxo: Utxo, };
