// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { P2PAddress } from "./P2PAddress";
import type { Utxo } from "./Utxo";

export type ProgramSetupRequest = { 
/**
 * The program ID
 */
program_id: string, 
/**
 * The participants
 */
participants: Array<P2PAddress>, 
/**
 * The aggregated key
 */
aggregated_key: string, 
/**
 * The initial utxo
 */
initial_utxo: Utxo, 
/**
 * The prover win utxo
 */
prover_win_utxo: Utxo, };
