// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SendFundsRequest = { 
/**
 * The destination hex public key or address to send funds to
 */
destination: string, 
/**
 * The scripts in hex format if its a P2TR x only public key destination
 */
scripts: Array<string> | null, 
/**
 * The amount to send in satoshis
 */
amount: bigint, };
