// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetupParticipantsResponse = { 
/**
 * The generated program ID, this is the program id that will be used to identify the game
 */
program_id: string, 
/**
 * The aggregated key
 */
aggregated_key: string, };
