// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { P2PAddress } from "./P2PAddress";

export type SetupParticipantsRequest = {
  /**
   * The UUID of the aggregated key, must be the same for all participants
   */
  aggregated_id: string;
  /**
   * The P2P addresses of the bitvmx nodes in the aggregated key
   */
  participants_addresses: Array<P2PAddress>;
  /**
   * The operator keys in hex format
   */
  participants_keys: Array<string>;
  /**
   * The leader index of the aggregated key
   */
  leader_idx: number;
};
