// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { P2PAddress } from "./P2PAddress";

export type SetupKey = { id: string, addresses: Array<P2PAddress>, };
