// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type SubmitSumResponse = { program_id: string, challenge_input_tx: JsonValue, challenge_result_tx: JsonValue, };
