// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TransactionResponse = { 
/**
 * The transaction ID
 */
txid: string, 
/**
 * The transaction status
 */
status: string, 
/**
 * The number of confirmations
 */
confirmations: number, 
/**
 * The block height
 */
block_height: number, 
/**
 * The block hash
 */
block_hash: string, };
