// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type Utxo = { 
/**
 * The transaction ID of the sent funds
 */
txid: string, 
/**
 * The output index
 */
vout: number, 
/**
 * The amount in satoshis
 */
amount: bigint, 
/**
 * The output type
 */
output_type: JsonValue, };
